### ISSUE TITLE
container won't start

### ISSUE THREAD

**Issue by mme89** [brunneis/tor-relay-docker#4] opened 2018-08-02 20:10 UTC
hi,
I am trying to run a middle relay, but the container doesn't start.
in the log there is only "No passwd entry for user 'tor' ", any idea?

thanks

**Comment by brunneis** [comment] 2018-08-02 20:20
Hi @teminvictus,

Are you launching a built image or building one yourself? Alpha or stable version?
Add also the command you've used to launch the container so I can replicate the error easily.

**Comment by mme89** [comment] 2018-08-03 11:04
Launching with your launch-relay script.
I just changed the contact info and nickname.

./launch-relay.sh brunneis/tor-relay:x86-64 middle

**Comment by brunneis** [comment] 2018-08-03 18:25
I have the following output in a clean Ubuntu VM:
```
./launch-relay.sh brunneis/tor-relay:x86-64 middle
```
```
docker logs tor-middle-relay
Aug 03 18:17:15.726 [notice] Tor 0.3.4.2-alpha (git-bc951e83aac770d1) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2g, Zlib 1.2.8, Liblzma N/A, and Libzstd N/A.
Aug 03 18:17:15.726 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Aug 03 18:17:15.726 [notice] This version is not a stable Tor release. Expect more bugs than usual.
Aug 03 18:17:15.726 [notice] Read configuration file "/home/tor/torrc".
Aug 03 18:17:15.729 [warn] ControlPort is open, but no authentication method has been configured.  This means that any program on your computer can reconfigure your Tor.  That's bad!  You should upgrade your Tor controller as soon as possible.
Aug 03 18:17:15.729 [notice] Scheduler type KIST has been enabled.
Aug 03 18:17:15.730 [notice] Opening Control listener on 127.0.0.1:9051
Aug 03 18:17:15.730 [notice] Opening OR listener on 0.0.0.0:9001
Aug 03 18:17:15.730 [notice] Opening Directory listener on 0.0.0.0:9030
Aug 03 18:17:15.730 [warn] Fixing permissions on directory /home/tor/data
Aug 03 18:17:15.000 [notice] Not disabling debugger attaching for unprivileged users.
Aug 03 18:17:15.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
Aug 03 18:17:15.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
Aug 03 18:17:15.000 [notice] Configured to measure statistics. Look for the *-stats files that will first be written to the data directory in 24 hours from now.
Aug 03 18:17:15.000 [notice] You are running a new relay. Thanks for helping the Tor network! If you wish to know what will happen in the upcoming weeks regarding its usage, have a look at https://blog.torproject.org/blog/lifecycle-of-a-new-relay
Aug 03 18:17:15.000 [notice] It looks like I need to generate and sign a new medium-term signing key, because I don't have one. To do that, I need to load (or create) the permanent master identity key. If the master identity key was not moved or encrypted with a passphrase, this will be done automatically and no further action is required. Otherwise, provide the necessary data using 'tor --keygen' to do it manually.
Aug 03 18:17:16.000 [notice] Your Tor server's identity key fingerprint is 'NotProvided 262AA00AEEE736885C37D0717D2C2C4F61ABAE7E'
Aug 03 18:17:16.000 [notice] Bootstrapped 0%: Starting
Aug 03 18:17:16.000 [notice] Starting with guard context "default"
Aug 03 18:17:16.000 [notice] Guessed our IP address as 91.116.186.158 (source: 193.23.244.244).
Aug 03 18:17:17.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Aug 03 18:17:18.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Aug 03 18:17:22.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Aug 03 18:17:22.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6438, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Aug 03 18:17:24.000 [notice] Bootstrapped 50%: Loading relay descriptors
Aug 03 18:17:26.000 [notice] Bootstrapped 55%: Loading relay descriptors
Aug 03 18:17:26.000 [notice] Bootstrapped 60%: Loading relay descriptors
Aug 03 18:17:27.000 [notice] Bootstrapped 65%: Loading relay descriptors
Aug 03 18:17:27.000 [notice] Bootstrapped 71%: Loading relay descriptors
Aug 03 18:17:27.000 [notice] Bootstrapped 77%: Loading relay descriptors
Aug 03 18:17:29.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Aug 03 18:17:31.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Aug 03 18:17:32.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Aug 03 18:17:33.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Aug 03 18:17:33.000 [notice] Bootstrapped 100%: Done
Aug 03 18:17:33.000 [notice] Now checking whether ORPort 91.116.186.158:9001 and DirPort 91.116.186.158:9030 are reachable... (this may take up to 20 minutes -- look for log messages indicating success)
```

**Comment by brunneis** [comment] 2018-08-03 19:41
Ok, the problem was you were executing the script as root. Please execute the script as an ordinary user.
```
sudo ./launch-relay.sh brunneis/tor-relay:x86-64 middle
```
```
$ docker logs tor-middle-relay
No passwd entry for user 'tor'
```

Anyway, the problem is now fixed: https://github.com/brunneis/tor-relay-docker/commit/92d5b0ee6863c21b08f25837dac1f5ccddee89de

**Closed as completed by brunneis** 2018-08-03 19:41 UTC

**Comment by arthurbre** [comment] 2019-02-12 10:01
Hello,
Sorry for commenting this issue unless it has been closed, but my problem is exactly what it describes...

I'm trying to run a middle relay on a Raspberry Pi. For now, just to test my setup, I tried to simply run the launch-relay.sh script without any customization.
The Raspberry Pi is running an up-to-date Raspbian Stretch.
So I ran the command:
$ sudo bash launch-relay.sh brunneis/tor-relay-arm:armhf middle
That pulled and ran a container.

$ sudo docker logs -f tor-middle-relay
No passwd entry for user 'tor'.

Yes, I'm running the script as root, which was originally the cause of this issue. But as you see, it still fails here and I don't understand why.

Any hint?

Anyway thanks for publishing these images. Love to play / experiment with Docker. :)

**Comment by brunneis** [comment] 2019-02-12 10:42
Hi, I think that the ARM images are outdated. Thank you for noticing @arthurbre!  I'll update them.

**Comment by brunneis** [comment] 2019-02-12 12:28
The images are updated, you can try again now @arthurbre.

**Comment by arthurbre** [comment] 2019-02-12 19:29
Thank you @brunneis , works perfectly! :)
